# Generated by Django 6.0 on 2026-03-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='dietary_prefs',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='privacy_consents',
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='login_status',
            field=models.CharField(default='first_login', max_length=20),
        ),
    ]
