# Generated by Django 6.0 on 2026-04-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_playerprofile_dietary_prefs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='player_avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
