# Generated by Django 6.0 on 2026-04-03 17:20

from django.db import migrations, models
import django.db.models.deletion


POSITION_SEED_DATA = [
    {"id": 1, "name": "Goalkeeper", "code": "GK", "category": "Defense"},
    {"id": 2, "name": "Center Back", "code": "CB", "category": "Defense"},
    {"id": 3, "name": "Right Back", "code": "RB", "category": "Defense"},
    {"id": 4, "name": "Left Back", "code": "LB", "category": "Defense"},
    {"id": 5, "name": "Defensive Midfielder", "code": "CDM", "category": "Midfield"},
    {"id": 6, "name": "Central Midfielder", "code": "CM", "category": "Midfield"},
    {"id": 7, "name": "Attacking Midfielder", "code": "CAM", "category": "Midfield"},
    {"id": 8, "name": "Right Midfielder", "code": "RM", "category": "Midfield"},
    {"id": 9, "name": "Left Midfielder", "code": "LM", "category": "Midfield"},
    {"id": 10, "name": "Right Winger", "code": "RW", "category": "Attack"},
    {"id": 11, "name": "Left Winger", "code": "LW", "category": "Attack"},
    {"id": 12, "name": "Striker", "code": "ST", "category": "Attack"},
    {"id": 13, "name": "Center Forward", "code": "CF", "category": "Attack"},
]


def _canonical_position_name(raw_value):
    if not raw_value:
        return None

    normalized = " ".join(str(raw_value).replace("-", " ").split()).strip().lower()
    if not normalized:
        return None

    mapping = {}
    for entry in POSITION_SEED_DATA:
        mapping[entry["name"].lower()] = entry["name"]
        mapping[entry["code"].lower()] = entry["name"]

    mapping.update(
        {
            "goalie": "Goalkeeper",
            "centre back": "Center Back",
            "center midfielder": "Central Midfielder",
            "centre midfielder": "Central Midfielder",
            "midfielder": "Central Midfielder",
            "defensive midfielder": "Defensive Midfielder",
            "attacking midfielder": "Attacking Midfielder",
            "right wing": "Right Winger",
            "left wing": "Left Winger",
            "right winger": "Right Winger",
            "left winger": "Left Winger",
            "forward": "Striker",
            "striker": "Striker",
            "centre forward": "Center Forward",
            "center forward": "Center Forward",
        }
    )
    return mapping.get(normalized)


def seed_positions_and_link_players(apps, schema_editor):
    Position = apps.get_model("accounts", "Position")
    PlayerProfile = apps.get_model("accounts", "PlayerProfile")

    positions_by_name = {}
    for entry in POSITION_SEED_DATA:
        position, _ = Position.objects.update_or_create(
            id=entry["id"],
            defaults={
                "name": entry["name"],
                "code": entry["code"],
                "category": entry["category"],
            },
        )
        positions_by_name[position.name] = position.id

    for profile in PlayerProfile.objects.all():
        canonical_name = _canonical_position_name(profile.position_label)
        if not canonical_name:
            continue

        profile.position_id = positions_by_name[canonical_name]
        profile.position_label = canonical_name
        profile.save(update_fields=["position", "position_label"])


def unseed_positions_and_unlink_players(apps, schema_editor):
    Position = apps.get_model("accounts", "Position")
    PlayerProfile = apps.get_model("accounts", "PlayerProfile")

    PlayerProfile.objects.update(position_id=None)
    Position.objects.filter(id__in=[entry["id"] for entry in POSITION_SEED_DATA]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_playerprofile_avatar_user_last_seen_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                ("id", models.PositiveSmallIntegerField(editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=60, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("category", models.CharField(max_length=30)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.RenameField(
            model_name="playerprofile",
            old_name="position",
            new_name="position_label",
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="player_profiles",
                to="accounts.position",
            ),
        ),
        migrations.RunPython(seed_positions_and_link_players, unseed_positions_and_unlink_players),
    ]
