# Generated by Django 6.0 on 2026-04-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_coachprofile_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachprofile',
            name='approval_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
