# Generated by Django 6.0 on 2026-04-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_coachprofile_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='foot',
            field=models.CharField(blank=True, choices=[('right', 'Right'), ('left', 'Left'), ('both', 'Both')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='state',
            field=models.CharField(choices=[('active', 'Active'), ('injured', 'Injured'), ('needs_review', 'Needs Review')], default='active', max_length=20),
        ),
    ]
