# Generated by Django 6.0 on 2026-04-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_remove_playerprofile_position_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
