# Generated by Django 6.0 on 2026-04-09 15:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_player_phone_to_user(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    PlayerProfile = apps.get_model('accounts', 'PlayerProfile')

    for profile in PlayerProfile.objects.exclude(phone__isnull=True).exclude(phone="").iterator():
        user = User.objects.filter(pk=profile.user_id).first()
        if user is not None and not user.phone:
            user.phone = profile.phone
            user.save(update_fields=['phone'])


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_first_name_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='PlayerPerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('speed', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('stamina', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('strength', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('skills', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('note', models.TextField(blank=True)),
                ('focus_area_override', models.CharField(blank=True, max_length=50)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_snapshots', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_player_performance_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at', '-id'],
                'indexes': [models.Index(fields=['player', 'recorded_at'], name='accounts_pl_player__126858_idx')],
            },
        ),
        migrations.RunPython(copy_player_phone_to_user, noop_reverse),
        migrations.RemoveField(
            model_name='playerprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='phone',
        ),
    ]
