# Generated by Django 6.0 on 2026-04-09 18:28

from django.db import migrations, models


def normalize_player_login_statuses(apps, schema_editor):
    PlayerProfile = apps.get_model('accounts', 'PlayerProfile')
    PlayerProfile.objects.filter(login_status__iexact='first_login').update(login_status='FIRST_LOGIN')
    PlayerProfile.objects.filter(login_status__iexact='complete').update(login_status='COMPLETE')
    PlayerProfile.objects.filter(login_status__iexact='completed').update(login_status='COMPLETE')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_playerprofile_age_remove_playerprofile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='foot',
            field=models.CharField(blank=True, choices=[('right', 'RIGHT'), ('left', 'left'), ('both', 'BOTH')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='login_status',
            field=models.CharField(default='FIRST_LOGIN', max_length=20),
        ),
        migrations.RunPython(normalize_player_login_statuses, migrations.RunPython.noop),
    ]
