# Generated by Django 6.0 on 2026-04-18 18:59

from django.db import migrations, models


UPPERCASE_SQL = [
    "UPDATE accounts_passwordsetuptoken SET purpose = UPPER(purpose) "
    "WHERE purpose <> UPPER(purpose);",
    "UPDATE accounts_playerprofile SET foot = UPPER(foot) "
    "WHERE foot IS NOT NULL AND foot <> UPPER(foot);",
    "UPDATE accounts_playerprofile SET state = UPPER(state) "
    "WHERE state <> UPPER(state);",
]

LOWERCASE_SQL = [
    "UPDATE accounts_passwordsetuptoken SET purpose = LOWER(purpose);",
    "UPDATE accounts_playerprofile SET foot = LOWER(foot) WHERE foot IS NOT NULL;",
    "UPDATE accounts_playerprofile SET state = LOWER(state);",
]


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_playerprofile_foot_and_more'),
    ]

    operations = [
        migrations.RunSQL(sql=UPPERCASE_SQL, reverse_sql=LOWERCASE_SQL),
        migrations.AlterField(
            model_name='passwordsetuptoken',
            name='purpose',
            field=models.CharField(choices=[('SET_PASSWORD', 'Set Password')], default='SET_PASSWORD', max_length=32),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='foot',
            field=models.CharField(blank=True, choices=[('RIGHT', 'Right'), ('LEFT', 'Left'), ('BOTH', 'Both')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='state',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INJURED', 'Injured'), ('NEEDS_REVIEW', 'Needs Review')], default='ACTIVE', max_length=20),
        ),
    ]
