# Generated by Django 6.0 on 2026-04-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_uppercase_enum_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='expected_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunSQL(
            sql="UPDATE accounts_playerprofile SET state = 'ACTIVE' WHERE state = 'NEEDS_REVIEW';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='state',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INJURED', 'Injured')], default='ACTIVE', max_length=20),
        ),
    ]
