# Generated by Codex on 2026-05-22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aiplandraft",
            name="target_players",
            field=models.ManyToManyField(
                blank=True,
                related_name="ai_plan_drafts_as_target",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
