# Generated by Django 6.0 on 2026-02-05 01:57

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingplan',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='duration_days',
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 1, 7)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 1, 7)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='status',
            field=models.CharField(default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='players',
            field=models.ManyToManyField(related_name='assigned_training_plans', through='training.TrainingPlanPlayer', through_fields=('plan', 'player'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainingplanplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
