# Generated by Django 6.0 on 2026-02-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_playersessionprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playersessionprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Completed')], default='not_started', max_length=20),
        ),
    ]
