# Generated by Django 6.0 on 2026-04-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_alter_playersessionprogress_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='session_type',
            field=models.CharField(choices=[('group', 'Group'), ('team', 'Team'), ('individual', 'Individual')], default='group', max_length=20),
        ),
    ]
