# Generated by Django 6.0 on 2026-04-17 12:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_player_checkin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='coach_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='intensity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='squad_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('tag', models.CharField(choices=[('load', 'Load'), ('intensity', 'Intensity'), ('recovery', 'Recovery')], max_length=15)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('player', 'date', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyLoad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start', models.DateField()),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('acute_load', models.IntegerField(default=0)),
                ('chronic_load', models.IntegerField(default=0)),
                ('sessions_completed', models.PositiveIntegerField(default=0)),
                ('sessions_planned', models.PositiveIntegerField(default=0)),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('top_sprint_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('top_sprint_pb_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_loads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('player', 'week_start')},
            },
        ),
    ]
