# Generated by Django 6.0 on 2026-04-18 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_home_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='duration_minutes',
        ),
    ]
