# Generated by Django 6.0 on 2026-04-18 18:59

from django.db import migrations, models


UPPERCASE_SQL = [
    "UPDATE training_aiinsight SET tag = UPPER(tag) WHERE tag <> UPPER(tag);",
    "UPDATE training_playercheckin SET sleep_quality = UPPER(sleep_quality) "
    "WHERE sleep_quality <> UPPER(sleep_quality);",
    "UPDATE training_playersessionprogress SET status = UPPER(status) "
    "WHERE status <> UPPER(status);",
    # Legacy alias: old "complete" rows should map to canonical "COMPLETED".
    "UPDATE training_playersessionprogress SET status = 'COMPLETED' "
    "WHERE status = 'COMPLETE';",
    "UPDATE training_sessionattendance SET status = UPPER(status) "
    "WHERE status <> UPPER(status);",
    "UPDATE training_sessionlifecycle SET status = UPPER(status) "
    "WHERE status <> UPPER(status);",
    "UPDATE training_trainingplan SET status = UPPER(status) "
    "WHERE status <> UPPER(status);",
    "UPDATE training_trainingsession SET intensity = UPPER(intensity) "
    "WHERE intensity <> UPPER(intensity);",
    "UPDATE training_trainingsession SET session_type = UPPER(session_type) "
    "WHERE session_type <> UPPER(session_type);",
]

LOWERCASE_SQL = [
    "UPDATE training_aiinsight SET tag = LOWER(tag);",
    "UPDATE training_playercheckin SET sleep_quality = LOWER(sleep_quality);",
    "UPDATE training_playersessionprogress SET status = LOWER(status);",
    "UPDATE training_sessionattendance SET status = LOWER(status);",
    "UPDATE training_sessionlifecycle SET status = LOWER(status);",
    "UPDATE training_trainingplan SET status = LOWER(status);",
    "UPDATE training_trainingsession SET intensity = LOWER(intensity);",
    "UPDATE training_trainingsession SET session_type = LOWER(session_type);",
]


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_sessionattendance_id_db_default'),
    ]

    operations = [
        migrations.RunSQL(sql=UPPERCASE_SQL, reverse_sql=LOWERCASE_SQL),
        migrations.AlterField(
            model_name='aiinsight',
            name='tag',
            field=models.CharField(choices=[('LOAD', 'Load'), ('INTENSITY', 'Intensity'), ('RECOVERY', 'Recovery')], max_length=15),
        ),
        migrations.AlterField(
            model_name='playercheckin',
            name='sleep_quality',
            field=models.CharField(choices=[('POOR', 'Poor'), ('FAIR', 'Fair'), ('GOOD', 'Good'), ('GREAT', 'Great')], max_length=10),
        ),
        migrations.AlterField(
            model_name='playersessionprogress',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='sessionattendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late')], default='PRESENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='sessionlifecycle',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='status',
            field=models.CharField(default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='intensity',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='session_type',
            field=models.CharField(choices=[('GROUP', 'Group'), ('TEAM', 'Team'), ('INDIVIDUAL', 'Individual')], default='GROUP', max_length=20),
        ),
    ]
