# Generated by Django 6.0 on 2026-04-24 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_uppercase_enum_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='coach_note',
        ),
    ]
